# Generated by Django 4.1.2 on 2022-11-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('gender', models.BooleanField(default=1)),
                ('birth', models.DateField()),
                ('department', models.CharField(max_length=30)),
                ('salary', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
    ]
