# Generated by Django 4.1.2 on 2022-11-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_employee_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
    ]
